language: python
sudo: false
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - SIMPHONY_VERSION=master MAYAVI_VERSION=master
  - SIMPHONY_VERSION=0.3.0 MAYAVI_VERSION=4.4.3  
matrix:
  allow_failures:
    - env: SIMPHONY_VERSION=master MAYAVI_VERSION=master
addons:
  apt:
    packages:
    - python-vtk
    - python-qt4
    - python-qt4-gl
    - python-imaging
    - python-pip
    - libhdf5-serial-dev
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
  - export ETS_TOOLKIT=qt4
  - export DISPLAY=:99.0
  - export VTKDATA=/home/travis/VTKData
  - git clone --depth=1 --branch=master git://vtk.org/VTKData.git /home/travis/VTKData
  - sh -e /etc/init.d/xvfb start
install:
  # see issue https://github.com/enthought/traitsui/issues/206
  - pip install traitsui!=4.5.0
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install git+https://github.com/simphony/simphony-common.git@${SIMPHONY_VERSION}#egg=simphony
  - pip install git+https://github.com/enthought/mayavi.git@${MAYAVI_VERSION}#egg=mayavi
- python setup.py develop
script:
  - flake8 .
  - coverage run -m unittest discover -v
after_success:
  - pip install codecov
  - codecov
