language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - add-apt-repository ppa:cython-dev/master-ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-serial-dev python-vtk python-qt4 python-qt4-dev python-sip python-qt4-gl libqt4-scripttools cython
  - export ETS_TOOLKIT=qt4
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - python setup.py develop
script:
  - flake8 .
  - coverage run -m haas
after_success:
  - coveralls
