language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-serial-dev python-vtk python-qt4 python-qt4-dev python-sip python-qt4-gl libqt4-scripttools
  - export ETS_TOOLKIT=qt4
install:
  # (1) Install cython and numexpr externally because the requirements does
  #     work with them
  # (2) Pytables breaks with latest Cython
  #     see https://github.com/PyTables/PyTables/issues/388
  - pip install numexpr cython==0.20
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - python setup.py develop
script:
  - flake8 .
  - coverage run -m haas
after_success:
  - coveralls
